services:
  node:
    depends_on:
      mariadb:
        condition: service_healthy
    image: ghcr.io/alexispet/final-test-thibaut-lecee/nodeexpress:develop
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - frontend
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.express-dev.rule=Host(`ec2-52-6-190-105.compute-1.amazonaws.com`)"
      - "traefik.http.routers.express-dev.entrypoints=web"
#      - "traefik.http.routers.express-dev.tls.certresolver=myresolver"
  mariadb:
    image: mariadb:11.2.2
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 20s
      retries: 10


networks:
  frontend:
    external: true
    name: custom_frontend

  backend:
    external: true
    name: custom_backend
