services:
  node:
    image: ghcr.io/alexispet/final-test-thibaut-lecee/nodeexpress:develop
    ports:
      - "3001:3001"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      NODE_ENV: development
    env_file:
      - .env

  mariadb:
    image: mariadb:11.2.2
    environment:
      MARIADB_HOST: mariadb
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"